# Monolithic build of the Influence Scraper codebase.
# Generated by flattening the previous module layout into one file.
# ===== BEGIN config\config.py =====
import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "env", ".env"))


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _env_list(name: str, default: list[str]) -> list[str]:
    raw_value = os.getenv(name)
    if not raw_value:
        return default
    return [item.strip().lstrip("#") for item in raw_value.split(",") if item.strip()]


# Database Config
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
DB_NAME = os.getenv("DB_NAME", "influencers_db")

# Scraping Config
SCRAPING_LIMITS = {
    "INSTAGRAM_POSTS": _env_int("INSTAGRAM_POSTS", 12),
    "INSTAGRAM_USERS_PER_HASHTAG": _env_int("INSTAGRAM_USERS_PER_HASHTAG", 25),
    "YOUTUBE_VIDEOS": _env_int("YOUTUBE_VIDEOS", 10),
}

# Runtime Config
ENABLE_INSTAGRAM = _env_bool("ENABLE_INSTAGRAM", True)
ENABLE_YOUTUBE = _env_bool("ENABLE_YOUTUBE", True)
HEADLESS_MODE = _env_bool("HEADLESS_MODE", True)
PROXY_URL = os.getenv("PROXY_URL", "").strip()
INSTAGRAM_SESSION_FILE = os.getenv("INSTAGRAM_SESSION_FILE", "session_state.json")
INSTAGRAM_USERNAME = os.getenv("INSTAGRAM_USERNAME", "").strip()
INSTAGRAM_PASSWORD = os.getenv("INSTAGRAM_PASSWORD", "").strip()

# Search Seeds
INSTAGRAM_HASHTAGS = _env_list("INSTAGRAM_HASHTAGS", ["indianfitness", "fitnessindia"])
YOUTUBE_KEYWORDS = _env_list("YOUTUBE_KEYWORDS", ["python tutorial", "tech reviews"])
YOUTUBE_SEARCH_RESULTS = _env_int("YOUTUBE_SEARCH_RESULTS", 3)
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")

# ===== END config\config.py =====

# ===== BEGIN utils\logger.py =====
import logging

def get_logger(name):
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)

    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter(
            "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)

    return logger
# ===== END utils\logger.py =====

# ===== BEGIN utils\helpers.py =====
import re

def clean_username(raw_username: str) -> str:
    """Removes @ and whitespace from instagram username."""
    if not raw_username:
        return ""
    return raw_username.replace("@", "").strip()

def parse_number(text: str) -> int:
    """
    Parses a string like '1.2M', '10K', '1,500' into an integer.
    """
    if not text:
        return 0
    
    text = text.upper().replace(",", "").replace(" ", "")
    
    multipliers = {'K': 1_000, 'M': 1_000_000, 'B': 1_000_000_000}
    
    for suffix, multiplier in multipliers.items():
        if suffix in text:
            try:
                num = float(text.replace(suffix, ""))
                return int(num * multiplier)
            except ValueError:
                return 0
    
    try:
        return int(float(text))
    except ValueError:
        return 0

def extract_hashtags(text: str) -> list[str]:
    """Extracts hashtags from a given string/caption."""
    if not text:
        return []
    return re.findall(r"#(\w+)", text)

# ===== END utils\helpers.py =====

# ===== BEGIN utils\rate_limiter.py =====
import time
import random

logger = get_logger(__name__)

def sleep_between_requests(min_seconds: float = 2.0, max_seconds: float = 5.0):
    """
    Sleep for a random amount of time between min_seconds and max_seconds
    to avoid rate limiting or being blocked.
    """
    sleep_time = random.uniform(min_seconds, max_seconds)
    logger.debug(f"Sleeping for {sleep_time:.2f} seconds...")
    time.sleep(sleep_time)

def handle_rate_limit(retry_after: int = 60):
    """
    Handle explicit rate limits (e.g., HTTP 429) by sleeping for a longer period.
    """
    logger.warning(f"Rate limited! Sleeping for {retry_after} seconds...")
    time.sleep(retry_after)

# ===== END utils\rate_limiter.py =====

# ===== BEGIN db\connection.py =====
import psycopg2
from psycopg2.extensions import connection

logger = get_logger(__name__)

def get_db_connection() -> connection:
    """
    Establishes and returns a connection to the PostgreSQL database.
    """
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD
        )
        return conn
    except Exception as e:
        logger.error(f"Failed to connect to database: {e}")
        raise

def init_db():
    """
    Initializes the database schema if it doesn't exist.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS influencers (
                id SERIAL PRIMARY KEY,
                platform VARCHAR(50) NOT NULL,
                username VARCHAR(255) UNIQUE NOT NULL,
                fullname VARCHAR(255),
                followers INT DEFAULT 0,
                bio TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)
        
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS posts (
                id SERIAL PRIMARY KEY,
                influencer_id INT REFERENCES influencers(id),
                post_url TEXT UNIQUE NOT NULL,
                likes INT DEFAULT 0,
                comments INT DEFAULT 0,
                views INT DEFAULT 0,
                posted_at TIMESTAMP,
                scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)
        
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS metrics (
                id SERIAL PRIMARY KEY,
                influencer_id INT REFERENCES influencers(id),
                engagement_rate FLOAT DEFAULT 0.0,
                avg_likes INT DEFAULT 0,
                avg_comments INT DEFAULT 0,
                calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)
        
        conn.commit()
        logger.info("Database schema initialized successfully.")
    except Exception as e:
        logger.error(f"Error initializing database: {e}")
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()

# ===== END db\connection.py =====

# ===== BEGIN db\db_writer.py =====

logger = get_logger(__name__)

def save_influencer(influencer_data: dict) -> int:
    """
    Saves or updates an influencer and returns their ID.
    Expects keys: platform, username, fullname, followers, bio
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    influencer_id = 0
    try:
        cursor.execute("""
            INSERT INTO influencers (platform, username, fullname, followers, bio)
            VALUES (%(platform)s, %(username)s, %(fullname)s, %(followers)s, %(bio)s)
            ON CONFLICT (username) 
            DO UPDATE SET 
                fullname = EXCLUDED.fullname,
                followers = EXCLUDED.followers,
                bio = EXCLUDED.bio
            RETURNING id;
        """, influencer_data)
        influencer_id = cursor.fetchone()[0]
        conn.commit()
        logger.info(f"Saved influencer {influencer_data.get('username')} with ID {influencer_id}")
    except Exception as e:
        logger.error(f"Error saving influencer: {e}")
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()
        
    return influencer_id

def save_posts(posts_data: list[dict]):
    """
    Saves a list of posts.
    Expects keys: influencer_id, post_url, likes, comments, views, posted_at
    """
    if not posts_data:
        return
        
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        for post in posts_data:
            cursor.execute("""
                INSERT INTO posts (influencer_id, post_url, likes, comments, views, posted_at)
                VALUES (%(influencer_id)s, %(post_url)s, %(likes)s, %(comments)s, %(views)s, %(posted_at)s)
                ON CONFLICT (post_url) 
                DO UPDATE SET 
                    likes = EXCLUDED.likes,
                    comments = EXCLUDED.comments,
                    views = EXCLUDED.views,
                    scraped_at = CURRENT_TIMESTAMP;
            """, post)
        conn.commit()
        logger.info(f"Saved {len(posts_data)} posts.")
    except Exception as e:
        logger.error(f"Error saving posts: {e}")
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()

def save_metrics(metrics_data: dict):
    """
    Saves calculated metrics for an influencer.
    Expects keys: influencer_id, engagement_rate, avg_likes, avg_comments
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            INSERT INTO metrics (influencer_id, engagement_rate, avg_likes, avg_comments)
            VALUES (%(influencer_id)s, %(engagement_rate)s, %(avg_likes)s, %(avg_comments)s);
        """, metrics_data)
        conn.commit()
        logger.info(f"Saved metrics for influencer ID {metrics_data.get('influencer_id')}")
    except Exception as e:
        logger.error(f"Error saving metrics: {e}")
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()

# ===== END db\db_writer.py =====

# ===== BEGIN pipeline\cleaner.py =====

logger = get_logger(__name__)

def clean_influencer_data(raw_data: dict) -> dict:
    """
    Cleans influencer data (e.g. handles missing bio, null followers)
    """
    cleaned = raw_data.copy()
    
    if not cleaned.get("bio"):
        cleaned["bio"] = ""
        
    followers = cleaned.get("followers")
    if not isinstance(followers, int) or (followers is not None and followers < 0):
        cleaned["followers"] = 0
        
    return cleaned

def clean_posts_data(raw_posts: list[dict]) -> list[dict]:
    """
    Remove duplicates and handle missing values in posts list.
    """
    if not raw_posts:
        return []
        
    # Remove duplicates based on URL
    seen_urls = set()
    cleaned_posts = []
    
    for post in raw_posts:
        url = post.get("post_url")
        if url in seen_urls:
            continue
            
        seen_urls.add(url)
        
        # Ensure numerics are intact
        for key in ["likes", "comments", "views"]:
            val = post.get(key)
            if not isinstance(val, int) or (val is not None and val < 0):
                post[key] = 0
                
        cleaned_posts.append(post)
        
    return cleaned_posts

# ===== END pipeline\cleaner.py =====

# ===== BEGIN pipeline\metrics.py =====

logger = get_logger(__name__)

def calculate_engagement(followers: int, posts: list[dict]) -> dict:
    """
    Calculates avg likes, avg comments, and overall engagement rate.
    Engagement Rate = ((Avg Likes + Avg Comments) / Followers) * 100
    """
    if not posts:
        return {
            "engagement_rate": 0.0,
            "avg_likes": 0,
            "avg_comments": 0
        }
        
    total_likes = sum(p.get("likes", 0) for p in posts)
    total_comments = sum(p.get("comments", 0) for p in posts)
    
    num_posts = len(posts)
    avg_likes = total_likes // num_posts
    avg_comments = total_comments // num_posts
    
    engagement_rate = 0.0
    if followers > 0:
        engagement_rate = ((avg_likes + avg_comments) / followers) * 100.0
        
    return {
        "engagement_rate": float(f"{engagement_rate:.2f}"),
        "avg_likes": avg_likes,
        "avg_comments": avg_comments
    }

# ===== END pipeline\metrics.py =====

# ===== BEGIN pipeline\processor.py =====

logger = get_logger(__name__)

from typing import Optional

def process_and_store_influencer(raw_profile: dict, raw_posts: Optional[list[dict]] = None) -> int:
    """
    Coordinates the pipeline: cleans data, calculates metrics, saves to DB.
    Returns the database ID of the influencer.
    """
    logger.info(f"Processing data for {raw_profile.get('username')}")
    
    # 1. Clean Data
    profile = clean_influencer_data(raw_profile)
    posts = clean_posts_data(raw_posts) if raw_posts else []
    
    # 2. Store Influencer (we need ID for posts/metrics)
    influencer_id = save_influencer(profile)
    
    # 3. Store Posts
    if posts:
        # Add influencer_id to each post
        for post in posts:
            post["influencer_id"] = influencer_id
        save_posts(posts)
        
    # 4. Calculate & Store Metrics
    metrics = calculate_engagement(profile.get("followers", 0), posts)
    metrics["influencer_id"] = influencer_id
    save_metrics(metrics)
    
    logger.info(f"Pipeline complete for {profile.get('username')}")
    return influencer_id

# ===== END pipeline\processor.py =====

# ===== BEGIN instagram\parsers.py =====
import re
from html import unescape


MEDIA_PATH_PATTERN = re.compile(r'href=["\'](/(?:reel|p|tv)/[^"\']+/?)["\']', re.IGNORECASE)
USERNAME_PATH_PATTERN = re.compile(r'href=["\']/([A-Za-z0-9._]+)/?["\']')
FULLNAME_PATTERN = re.compile(r"from\s+(?P<fullname>.+?)\s+\(@(?P<username>[A-Za-z0-9._]+)\)", re.IGNORECASE)
FOLLOWERS_PATTERN = re.compile(r"(?P<followers>[0-9.,KMB]+)\s+Followers", re.IGNORECASE)
LIKES_PATTERN = re.compile(r"(?P<likes>[0-9.,KMB]+)\s+Likes?", re.IGNORECASE)
COMMENTS_PATTERN = re.compile(r"(?P<comments>[0-9.,KMB]+)\s+Comments?", re.IGNORECASE)
VIEWS_PATTERN = re.compile(r"(?P<views>[0-9.,KMB]+)\s+(?:Views?|Plays?)", re.IGNORECASE)

RESERVED_SEGMENTS = {
    "about",
    "accounts",
    "api",
    "challenge",
    "developer",
    "direct",
    "download",
    "explore",
    "graphql",
    "legal",
    "oauth",
    "p",
    "popular",
    "press",
    "reel",
    "reels",
    "stories",
    "tags",
    "tv",
    "web",
}


def normalize_instagram_path(path: str) -> str:
    path = (path or "").strip()
    if not path:
        return ""
    if not path.startswith("/"):
        path = f"/{path}"
    if not path.endswith("/"):
        path = f"{path}/"
    return path


def is_valid_instagram_username(candidate: str) -> bool:
    if not candidate:
        return False

    normalized = candidate.strip().strip("/").lower()
    if normalized in RESERVED_SEGMENTS:
        return False

    return bool(re.fullmatch(r"[A-Za-z0-9._]+", normalized))


def unique_ordered(values: list[str]) -> list[str]:
    seen = set()
    ordered = []

    for value in values:
        if value in seen:
            continue
        seen.add(value)
        ordered.append(value)

    return ordered


def extract_media_paths_from_html(html: str, limit: int | None = None) -> list[str]:
    matches = [normalize_instagram_path(match) for match in MEDIA_PATH_PATTERN.findall(html or "")]
    media_paths = unique_ordered([match for match in matches if match])
    return media_paths[:limit] if limit else media_paths


def extract_candidate_usernames_from_html(html: str, limit: int | None = None) -> list[str]:
    candidates = []

    for candidate in USERNAME_PATH_PATTERN.findall(html or ""):
        if is_valid_instagram_username(candidate):
            candidates.append(candidate.strip("/"))

    usernames = unique_ordered(candidates)
    return usernames[:limit] if limit else usernames


def parse_profile_meta_description(meta_description: str) -> dict:
    description = unescape(meta_description or "")
    parsed = {"fullname": "", "followers": 0}

    fullname_match = FULLNAME_PATTERN.search(description)
    if fullname_match:
        parsed["fullname"] = fullname_match.group("fullname").strip()

    followers_match = FOLLOWERS_PATTERN.search(description)
    if followers_match:
        parsed["followers"] = parse_number(followers_match.group("followers"))

    return parsed


def parse_post_meta_description(meta_description: str) -> dict:
    description = unescape(meta_description or "")
    parsed = {"likes": 0, "comments": 0, "views": 0}

    likes_match = LIKES_PATTERN.search(description)
    if likes_match:
        parsed["likes"] = parse_number(likes_match.group("likes"))

    comments_match = COMMENTS_PATTERN.search(description)
    if comments_match:
        parsed["comments"] = parse_number(comments_match.group("comments"))

    views_match = VIEWS_PATTERN.search(description)
    if views_match:
        parsed["views"] = parse_number(views_match.group("views"))

    return parsed

# ===== END instagram\parsers.py =====

# ===== BEGIN instagram\session.py =====
from pathlib import Path

from playwright.sync_api import Browser, BrowserContext, Page, Playwright, TimeoutError as PlaywrightTimeoutError

logger = get_logger(__name__)

INSTAGRAM_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
)
INSTAGRAM_VIEWPORT = {"width": 1280, "height": 800}
PROJECT_ROOT = Path(__file__).resolve().parent
SESSION_FILE_PATH = Path(INSTAGRAM_SESSION_FILE)
if not SESSION_FILE_PATH.is_absolute():
    SESSION_FILE_PATH = PROJECT_ROOT / SESSION_FILE_PATH


def launch_instagram_context(playwright: Playwright) -> tuple[Browser, BrowserContext, Page]:
    launch_options = {"headless": HEADLESS_MODE}
    if PROXY_URL:
        launch_options["proxy"] = {"server": PROXY_URL}

    browser = playwright.chromium.launch(**launch_options)

    context_options = {
        "user_agent": INSTAGRAM_USER_AGENT,
        "viewport": INSTAGRAM_VIEWPORT,
    }
    if SESSION_FILE_PATH.exists():
        context_options["storage_state"] = str(SESSION_FILE_PATH)

    context = browser.new_context(**context_options)
    page = context.new_page()
    return browser, context, page


def go_to_instagram_url(page: Page, context: BrowserContext, url: str) -> None:
    page.goto(url, wait_until="domcontentloaded", timeout=60000)

    if is_login_page(page):
        if not login_to_instagram(page, context):
            logger.warning("Instagram login was required but could not be completed.")
            return

        page.goto(url, wait_until="domcontentloaded", timeout=60000)


def is_login_page(page: Page) -> bool:
    return page.locator("input[name='username']").count() > 0 and page.locator("input[name='password']").count() > 0


def login_to_instagram(page: Page, context: BrowserContext) -> bool:
    if not INSTAGRAM_USERNAME or not INSTAGRAM_PASSWORD:
        logger.warning("Instagram credentials are not configured. Continuing without login.")
        return False

    logger.info("Attempting Instagram login to reuse an authenticated session.")

    try:
        if not is_login_page(page):
            page.goto("https://www.instagram.com/accounts/login/", wait_until="domcontentloaded", timeout=60000)

        dismiss_cookie_prompt(page)

        page.locator("input[name='username']").fill(INSTAGRAM_USERNAME)
        page.locator("input[name='password']").fill(INSTAGRAM_PASSWORD)
        page.locator("button[type='submit']").click()

        page.wait_for_timeout(4000)
        dismiss_optional_prompt(page)
        dismiss_optional_prompt(page)

        if is_login_page(page):
            logger.error("Instagram login appears to have failed. Check credentials or checkpoint prompts.")
            return False

        SESSION_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)
        context.storage_state(path=str(SESSION_FILE_PATH))
        logger.info("Saved Instagram session state for future runs.")
        return True
    except PlaywrightTimeoutError:
        logger.error("Timed out during Instagram login.")
        return False
    except Exception as exc:
        logger.error(f"Instagram login failed: {exc}")
        return False


def dismiss_cookie_prompt(page: Page) -> None:
    button_names = [
        "Allow all cookies",
        "Allow essential and optional cookies",
        "Only allow essential cookies",
    ]

    for name in button_names:
        try:
            button = page.get_by_role("button", name=name)
            if button.count() > 0:
                button.first.click()
                page.wait_for_timeout(1000)
                return
        except Exception:
            continue


def dismiss_optional_prompt(page: Page) -> None:
    for name in ["Not Now", "Cancel"]:
        try:
            button = page.get_by_role("button", name=name)
            if button.count() > 0:
                button.first.click()
                page.wait_for_timeout(1000)
                return
        except Exception:
            continue

# ===== END instagram\session.py =====

# ===== BEGIN instagram\hashtag_scraper.py =====
from playwright.sync_api import sync_playwright


logger = get_logger(__name__)


def _extract_username_from_media_page(page) -> str:
    for anchor in page.query_selector_all("header a[href]"):
        href = anchor.get_attribute("href") or ""
        parts = [part for part in href.split("/") if part]
        if not parts:
            continue

        candidate = parts[0]
        if candidate not in {"p", "reel", "reels", "explore"}:
            return str(candidate)

    usernames = extract_candidate_usernames_from_html(page.content(), limit=1)
    return str(usernames[0]) if usernames else ""


def get_usernames_from_hashtag(hashtag: str, max_users: int = 10) -> list[str]:
    """Scrape a hashtag page and return the usernames shown in the reel/post grid."""
    usernames = []
    url = f"https://www.instagram.com/explore/tags/{hashtag}/"
    logger.info(f"Scraping hashtag: #{hashtag} for up to {max_users} users")

    with sync_playwright() as p:
        browser, context, page = launch_instagram_context(p)

        try:
            go_to_instagram_url(page, context, url)
            sleep_between_requests(4, 6)

            media_paths = []
            for _ in range(8):
                html = page.content()
                usernames = extract_candidate_usernames_from_html(html, limit=max_users)
                media_paths = extract_media_paths_from_html(html, limit=max_users * 2)

                if len(usernames) >= max_users or len(media_paths) >= max_users:
                    break

                page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                sleep_between_requests(2, 4)

            logger.info(
                f"Discovered {len(usernames)} candidate usernames and {len(media_paths)} media links for #{hashtag}"
            )

            if len(usernames) < max_users:
                fallback_usernames = list(usernames)
                for media_path in media_paths:
                    if len(fallback_usernames) >= max_users:
                        break

                    try:
                        go_to_instagram_url(page, context, f"https://www.instagram.com{media_path}")
                        sleep_between_requests(2, 4)
                        username = _extract_username_from_media_page(page)
                        if username and username not in fallback_usernames:
                            fallback_usernames.append(username)
                    except Exception as exc:
                        logger.warning(f"Error extracting username from {media_path}: {exc}")

                usernames = fallback_usernames

            logger.info(f"Collected {len(usernames)} usernames from #{hashtag}")
        except Exception as exc:
            logger.error(f"Failed to scrape hashtag {hashtag}: {exc}")
            logger.warning("Instagram might be blocking the request or requiring login.")
        finally:
            browser.close()

    return [u for i, u in enumerate(usernames) if i < max_users]

# ===== END instagram\hashtag_scraper.py =====

# ===== BEGIN instagram\profile_scraper.py =====
import re

from playwright.sync_api import sync_playwright


logger = get_logger(__name__)


def _get_meta_description(page) -> str:
    selectors = ['meta[property="og:description"]', 'meta[name="description"]']
    for selector in selectors:
        locator = page.locator(selector)
        if locator.count() > 0:
            content = locator.first.get_attribute("content")
            if content:
                return content
    return ""


def _extract_bio(page, username: str) -> str:
    selectors = [
        "header section",
        "main header",
    ]

    for selector in selectors:
        try:
            element = page.query_selector(selector)
            if not element:
                continue

            lines = [line.strip() for line in element.inner_text().splitlines() if line.strip()]
            filtered = []
            for line in lines:
                lower_line = line.lower()
                if username.lower() in lower_line:
                    continue
                if any(token in lower_line for token in ["followers", "following", "posts", "message"]):
                    continue
                filtered.append(line)

            if filtered:
                return " ".join([f for i, f in enumerate(filtered) if i < 3])
        except Exception:
            continue

    return ""


def get_profile_data(username: str) -> dict:
    """Scrapes profile metadata like followers, bio, fullname."""
    url = f"https://www.instagram.com/{username}/"
    logger.info(f"Scraping profile: {username}")

    data = {"platform": "instagram", "username": username, "fullname": "", "followers": 0, "bio": ""}

    with sync_playwright() as p:
        browser, context, page = launch_instagram_context(p)
        try:
            go_to_instagram_url(page, context, url)
            sleep_between_requests(3, 5)

            title = page.title()
            title_match = re.search(r"^(.*?)\s*\(@", title)
            if title_match:
                data["fullname"] = title_match.group(1).strip()

            meta_desc = _get_meta_description(page)
            parsed_meta = parse_profile_meta_description(meta_desc)
            if parsed_meta["fullname"] and not data["fullname"]:
                data["fullname"] = parsed_meta["fullname"]
            data["followers"] = parsed_meta["followers"]
            data["bio"] = _extract_bio(page, username)

            logger.info(f"Successfully scraped profile {username} (Followers: {data['followers']})")
        except Exception as exc:
            logger.error(f"Failed to scrape profile {username}: {exc}")
        finally:
            browser.close()

    return data

# ===== END instagram\profile_scraper.py =====

# ===== BEGIN instagram\post_scraper.py =====
from typing import Optional

from playwright.sync_api import sync_playwright


logger = get_logger(__name__)


def _get_meta_description(page) -> str:
    selectors = ['meta[property="og:description"]', 'meta[name="description"]']
    for selector in selectors:
        locator = page.locator(selector)
        if locator.count() > 0:
            content = locator.first.get_attribute("content")
            if content:
                return content
    return ""


def get_recent_posts(username: str, limit: Optional[int] = None) -> list[dict]:
    """Scrapes the most recent posts for an Instagram user including extracted likes/comments."""
    if limit is None:
        limit = SCRAPING_LIMITS.get("INSTAGRAM_POSTS", 12)

    url = f"https://www.instagram.com/{username}/"
    logger.info(f"Scraping up to {limit} posts for {username}")

    posts = []
    with sync_playwright() as p:
        browser, context, page = launch_instagram_context(p)
        try:
            go_to_instagram_url(page, context, url)
            sleep_between_requests(3, 5)

            post_hrefs = []
            for _ in range(8):
                current_paths = extract_media_paths_from_html(page.content())
                for path in current_paths:
                    if path not in post_hrefs:
                        post_hrefs.append(path)

                if len(post_hrefs) >= limit:
                    break

                page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                sleep_between_requests(2, 4)

            limited_hrefs = [h for i, h in enumerate(post_hrefs) if i < limit]
            logger.info(f"Found {len(limited_hrefs)} media links. Extracting stats...")

            for href in limited_hrefs:
                post_url = f"https://www.instagram.com{href}"
                try:
                    go_to_instagram_url(page, context, post_url)
                    sleep_between_requests(2, 4)

                    parsed_meta = parse_post_meta_description(_get_meta_description(page))
                    time_locator = page.locator("time")
                    posted_at = None
                    if time_locator.count() > 0:
                        posted_at = time_locator.first.get_attribute("datetime")
                except Exception as exc:
                    logger.warning(f"Could not extract stats for {post_url}: {exc}")
                    parsed_meta = {"likes": 0, "comments": 0, "views": 0}
                    posted_at = None

                posts.append({
                    "post_url": post_url,
                    "likes": parsed_meta["likes"],
                    "comments": parsed_meta["comments"],
                    "views": parsed_meta["views"],
                    "posted_at": posted_at,
                })

            logger.info(f"Collected and parsed {len(posts)} posts for {username}")
        except Exception as exc:
            logger.error(f"Failed to scrape posts for {username}: {exc}")
        finally:
            browser.close()

    return posts

# ===== END instagram\post_scraper.py =====

# ===== BEGIN youtube\channel_finder.py =====
from googleapiclient.discovery import build

logger = get_logger(__name__)


def find_channels_by_keyword(keyword: str, max_results: int = 3) -> list[str]:
    """Search YouTube for a keyword and return a list of Channel IDs."""
    logger.info(f"Searching YouTube channels for keyword: '{keyword}'")

    if not YOUTUBE_API_KEY:
        logger.error("No YouTube API key found. Skipping YouTube channel search.")
        return []

    try:
        youtube = build("youtube", "v3", developerKey=YOUTUBE_API_KEY)
        request = youtube.search().list(
            q=keyword,
            part="id",
            type="channel",
            maxResults=max_results,
            regionCode="IN",
        )
        response = request.execute()

        channel_ids = []
        for item in response.get("items", []):
            channel_id = item.get("id", {}).get("channelId")
            if channel_id:
                channel_ids.append(channel_id)

        logger.info(f"Found {len(channel_ids)} channels for '{keyword}'")
        return channel_ids
    except Exception as exc:
        logger.error(f"YouTube search API failed: {exc}")
        return []

# ===== END youtube\channel_finder.py =====

# ===== BEGIN youtube\channel_scraper.py =====
from googleapiclient.discovery import build

logger = get_logger(__name__)


def get_channel_info(channel_id: str) -> dict:
    """Retrieve channel metadata (subscribers, views, name) using YouTube API."""
    logger.info(f"Scraping channel info for {channel_id}")

    data = {
        "platform": "youtube",
        "username": channel_id,
        "fullname": "",
        "followers": 0,
        "bio": "",
    }

    if not YOUTUBE_API_KEY:
        logger.error(f"No YouTube API key. Skipping channel lookup for {channel_id}.")
        return data

    try:
        youtube = build("youtube", "v3", developerKey=YOUTUBE_API_KEY)
        request = youtube.channels().list(
            part="snippet,statistics",
            id=channel_id,
        )
        response = request.execute()

        items = response.get("items", [])
        if items:
            channel = items[0]
            snippet = channel.get("snippet", {})
            stats = channel.get("statistics", {})

            data["fullname"] = snippet.get("title", "")
            data["bio"] = snippet.get("description", "")
            data["followers"] = int(stats.get("subscriberCount", 0))

            logger.info(f"Successfully scraped channel {data['fullname']} ({data['followers']} subs)")
        else:
            logger.warning(f"Channel {channel_id} not found.")
    except Exception as exc:
        logger.error(f"YouTube Channels API failed for {channel_id}: {exc}")

    return data

# ===== END youtube\channel_scraper.py =====

# ===== BEGIN youtube\video_scraper.py =====
from typing import Optional
from googleapiclient.discovery import build

logger = get_logger(__name__)


def get_recent_videos(channel_id: str, limit: Optional[int] = None) -> list[dict]:
    """Retrieve recent video stats (views, likes, comments) via YouTube API."""
    if limit is None:
        limit = SCRAPING_LIMITS.get("YOUTUBE_VIDEOS", 5)

    logger.info(f"Scraping up to {limit} recent videos for {channel_id}")

    videos = []

    if not YOUTUBE_API_KEY:
        logger.error(f"No YouTube API key. Skipping recent video lookup for {channel_id}.")
        return videos

    try:
        youtube = build("youtube", "v3", developerKey=YOUTUBE_API_KEY)

        search_req = youtube.search().list(
            part="id",
            channelId=channel_id,
            maxResults=limit,
            order="date",
            type="video",
        )
        search_resp = search_req.execute()

        video_ids = [item["id"]["videoId"] for item in search_resp.get("items", []) if "videoId" in item.get("id", {})]

        if not video_ids:
            logger.info(f"No videos found for channel {channel_id}")
            return videos

        videos_req = youtube.videos().list(
            part="snippet,statistics",
            id=",".join(video_ids),
        )
        videos_resp = videos_req.execute()

        for item in videos_resp.get("items", []):
            vid_id = item["id"]
            stats = item.get("statistics", {})
            snippet = item.get("snippet", {})

            videos.append({
                "post_url": f"https://www.youtube.com/watch?v={vid_id}",
                "likes": int(stats.get("likeCount", 0)),
                "comments": int(stats.get("commentCount", 0)),
                "views": int(stats.get("viewCount", 0)),
                "posted_at": snippet.get("publishedAt", None),
            })

        logger.info(f"Successfully scraped {len(videos)} videos for {channel_id}")
    except Exception as exc:
        logger.error(f"YouTube Videos API failed for {channel_id}: {exc}")

    return videos

# ===== END youtube\video_scraper.py =====

# ===== BEGIN main.py =====
import sys


logger = get_logger(__name__)


def run_instagram_scraper():
    """Run the core Instagram scraping pipeline."""

    for hashtag in INSTAGRAM_HASHTAGS:
        logger.info(f"--- Starting Instagram pipeline for hashtag: #{hashtag} ---")
        limit = SCRAPING_LIMITS.get("INSTAGRAM_USERS_PER_HASHTAG", 50)
        usernames = get_usernames_from_hashtag(hashtag, max_users=limit)

        if not usernames:
            logger.warning(f"No Instagram usernames found for #{hashtag}")
            continue

        for username in usernames:
            try:
                profile_data = get_profile_data(username)
                posts_data = get_recent_posts(username)
                process_and_store_influencer(profile_data, posts_data)
            except Exception as exc:
                logger.error(f"Failed to process Instagram user {username}: {exc}")


def run_youtube_scraper():
    """Run the secondary YouTube scraping pipeline."""
    for keyword in YOUTUBE_KEYWORDS:
        logger.info(f"--- Starting YouTube pipeline for keyword: '{keyword}' ---")
        channel_ids = find_channels_by_keyword(keyword, max_results=YOUTUBE_SEARCH_RESULTS)

        if not channel_ids:
            logger.warning(f"No YouTube channels found for '{keyword}'")
            continue

        for channel_id in channel_ids:
            try:
                channel_data = get_channel_info(channel_id)
                video_data = get_recent_videos(channel_id)
                process_and_store_influencer(channel_data, video_data)
            except Exception as exc:
                logger.error(f"Failed to process YouTube channel {channel_id}: {exc}")


def main():
    logger.info("Initializing Influencer Scraper MVP")

    try:
        init_db()
    except Exception as exc:
        logger.error(f"Could not initialize database: {exc}")
        logger.error("Please check database credentials or ensure PostgreSQL is running.")
        sys.exit(1)

    if not ENABLE_INSTAGRAM and not ENABLE_YOUTUBE:
        logger.warning("Both scraping pipelines are disabled. Enable at least one platform in the environment.")
        return

    if ENABLE_INSTAGRAM:
        run_instagram_scraper()

    if ENABLE_YOUTUBE:
        run_youtube_scraper()

    logger.info("Scraping run completed successfully.")


if __name__ == "__main__":
    main()

# ===== END main.py =====
